# Dependencies
markdown:         redcarpet
highlighter: pygments

# Permalinks
#permalink:        pretty
permalink: /posts/:title
#auto: true
rdiscount:
extensions: [smart]

# Setup
title:            Álvaro Felipe Melchor
tagline:          'Stuff about everything'
description:      'Stuff about everything'
url:              http://alvarofe.github.io 
baseurl:          /

author:
  name:           'Álvaro Felipe Melchor'
  url:            https://twitter.com/alvaro_fe

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alvarofe



