# Dependencies
# Gems
gems: [jekyll-paginate]
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
# Permalinks
#permalink:        pretty
permalink: /posts/:title
#auto: true
rdiscount:
extensions: [smart]

# Setup
title:            Álvaro 
tagline:          ''
description:      'Still learning'
url:              http://alvarofe.github.io 
baseurl:          /

author:
  name:           'Álvaro'
  url:            https://twitter.com/alvaro_fe

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alvarofe



